ALTER TABLE "organizations" ADD COLUMN "billing_name" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "billing_npi" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "billing_tax_id" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "billing_address_line_1" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "billing_city" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "billing_state" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "billing_zip_code" text;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "state_license_number" text;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "state_license_expiry" date;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "taxonomy_code" text;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "email" text;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "phone" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "secondary_diagnosis_codes" text[];--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "primary_language" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "interpreter_needed" boolean;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "referring_provider_name" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "referring_provider_npi" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "medicaid_id" text;--> statement-breakpoint
ALTER TABLE "payers" ADD COLUMN "electronic_payer_id" text;--> statement-breakpoint
ALTER TABLE "payers" ADD COLUMN "auth_department_email" text;--> statement-breakpoint
ALTER TABLE "payers" ADD COLUMN "portal_url" text;--> statement-breakpoint
ALTER TABLE "authorizations" ADD COLUMN "auth_type" text;--> statement-breakpoint
ALTER TABLE "authorizations" ADD COLUMN "requesting_provider_id" text;--> statement-breakpoint
ALTER TABLE "authorizations" ADD COLUMN "denial_reason" text;--> statement-breakpoint
ALTER TABLE "authorizations" ADD COLUMN "appeal_deadline" date;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "cancellation_reason" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "cancelled_by" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "service_address" text;